volumes:
  atmunge_db_data:

services:
  db:
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_DB: atmunge
      POSTGRES_USER: atmunge
      POSTGRES_PASSWORD: atmunge
    volumes:
      - /data/atmunge/postgres:/var/lib/postgresql
    ports:
    - "5555:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: blebbit/atmunge
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      db:
        condition: service_started
    environment:
      ATMUNGE_METRICS_PORT: '1323'
      ATMUNGE_POSTGRES_URL: "postgres://atmunge:atmunge@db/atmunge?sslmode=disable"
    ports:
      - "0.0.0.0:11004:1323"
    command: [ "--log-level=0", "--run-mirror=false" ]
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 30
    #   start_period: 12h
    #   start_interval: 15s

# pg_dump -U postgres -Z zstd plc > plc.sql.zst
